name: flutter_webrtc
description: Flutter WebRTC plugin for iOS/Android/Destkop/Web.
version: 1.0.0+1
homepage: https://github.com/cloudwebrtc/flutter-webrtc

dependencies:
  flutter:
    sdk: flutter
  http:
  path_provider: ^2.0.11
flutter:
  plugin:
    platforms:
      android:
        package: com.cloudwebrtc.webrtc
        pluginClass: FlutterWebRTCPlugin
      ios:
        pluginClass: FlutterWebRTCPlugin
      macos:
        pluginClass: FlutterWebRTCPlugin

environment:
  sdk: '2.17.5'
  flutter: ^1.10.0
